import { useEffect, useState } from 'react'
import { MapContainer, Marker, Polygon, TileLayer, useMapEvents } from 'react-leaflet'
import { createFarm, validateFarm } from '../api/farms'
import { searchFarmers } from '../api/farmers'
import { useAuth } from '../context/useAuth'
import 'leaflet/dist/leaflet.css'

function MapClicks({ mode, points, setPoints, point, setPoint }) { useMapEvents({ click(e) { const value = [e.latlng.lng, e.latlng.lat]; if (mode === 'polygon' && !points.some(([lng, lat]) => lng === value[0] && lat === value[1])) setPoints([...points, value]); else if (mode === 'point') setPoint(value) } }); return <>{points.length > 1 && <Polygon positions={points.map(([lng, lat]) => [lat, lng])} />}{point && <Marker position={[point[1], point[0]]} />}</> }

export default function FarmRegistration() {
  const { accessToken, role } = useAuth(); const canWrite = role === 'Admin' || role === 'Field/Registry Agent'
  const [farmers,setFarmers]=useState([]),[farmerId,setFarmerId]=useState(''),[mode,setMode]=useState('polygon'),[points,setPoints]=useState([]),[point,setPoint]=useState(null),[radius,setRadius]=useState('25'),[result,setResult]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[submitting,setSubmitting]=useState(false)
  useEffect(()=>{ let cancelled=false; searchFarmers('',accessToken).then(v=>!cancelled&&setFarmers(v)).catch(e=>!cancelled&&setError(e.message)).finally(()=>!cancelled&&setLoading(false)); return()=>{cancelled=true} },[accessToken])
  const submit=async e=>{e.preventDefault(); try { const radiusMeters=Number(radius); if(!accessToken) throw new Error('Your session has expired. Please sign in again.'); if(!farmerId) throw new Error('Select a farmer.'); if(mode==='polygon'&&points.length<6) throw new Error('Polygon mode requires at least six distinct vertices.'); if(mode==='point'&&(!point||!Number.isFinite(radiusMeters)||radiusMeters<=0)) throw new Error('Select a point and enter a positive radius.'); setSubmitting(true); const ring = mode === 'polygon' ? [...points, [...points[0]]] : null; const geometry=ring?{type:'Polygon',coordinates:[ring]}:{type:'Point',coordinates:[Number(point[0]),Number(point[1])]}; const payload={farmer_id:Number(farmerId),geometry}; if(mode==='point') payload.radius_meters=radiusMeters; setResult(await createFarm(payload,accessToken)); setError('') }catch(err){setError(err.message)}finally{setSubmitting(false)} }
  return <section className="farmer-page"><h1>Farm registration</h1>{!canWrite?<p>Farm creation is available to Admin and Field/Registry Agent roles.</p>:<form className="login-form" onSubmit={submit}><label>Farmer<select value={farmerId} onChange={e=>setFarmerId(e.target.value)}><option value="">{loading?'Loading farmers…':'Select a farmer'}</option>{farmers.map(f=><option key={f.farmer_id} value={f.farmer_id}>{f.full_name} — {f.fin_code}</option>)}</select></label><label><input type="radio" checked={mode==='polygon'} onChange={()=>setMode('polygon')}/> Polygon</label><label><input type="radio" checked={mode==='point'} onChange={()=>setMode('point')}/> Point + radius</label>{mode==='point'&&<label>Radius metres<input type="number" min="1" value={radius} onChange={e=>setRadius(e.target.value)}/></label>}<MapContainer center={[9,38.75]} zoom={13} style={{height:300}}><TileLayer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><MapClicks mode={mode} points={points} setPoints={setPoints} point={point} setPoint={setPoint}/></MapContainer><button type="button" onClick={()=>{setPoints([]);setPoint(null)}}>Clear map</button><p>{mode==='polygon'?`Click map to draw at least six vertices (${points.length} selected).`:'Click map to select the centre point.'}</p><button disabled={submitting}>{submitting?'Saving…':'Save farm'}</button></form>}{error&&<p className="form-error">{error}</p>}{result&&<article><h2>Farm {result.farm_id} saved</h2><p>Area: {result.area_hectares} hectares</p><p>Demonstration review flag: {String(result.eudr_risk_flag)}</p><p>{result.eudr_check_type}</p><button onClick={()=>validateFarm(result.farm_id,accessToken).then(setResult).catch(e=>setError(e.message))}>Re-validate</button></article>}</section>
}
